name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - unit_test

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: travel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASSWORD=123456" >> .env
          echo "DB_NAME=travel" >> .env

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Install wait-for-it
        run: |
          curl -sSL https://github.com/vishnubob/wait-for-it/releases/download/v2.5.0/wait-for-it.sh -o wait-for-it.sh
          chmod +x wait-for-it.sh
          
      - name: Start container (via Docker Compose)
        run: |
          docker-compose up --build -d
          ./wait-for-it.sh db:3306 --timeout=120 --strict -- echo "MySQL is ready!"
          
      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t hotels-service -f dockerfiles/app-dockerfile .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag hotels-service ${{ secrets.DOCKER_USERNAME }}/hotels-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/hotels-service:latest

      - name: Deploy to server
        run: |
          ssh user@your-server "docker pull ${{ secrets.DOCKER_USERNAME }}/hotels-service:latest && docker-compose up -d"
